export const accentHexMap = {
  orange: {
    name: "orange",
    displayName: "Orange",
    hex: "#f97316",
    bgClass: "bg-orange-500",
    hoverClass: "hover:bg-orange-600",
    txtClass: "text-orange-500",
    borderClass: "border-orange-500",
  },
  amber: {
    name: "amber",
    displayName: "Amber",
    hex: "#f59e0b",
    bgClass: "bg-amber-500",
    hoverClass: "hover:bg-amber-600",
    txtClass: "text-amber-500",
    borderClass: "border-amber-500",
  },
  yellow: {
    name: "yellow",
    displayName: "Yellow",
    hex: "#eab308",
    bgClass: "bg-yellow-500",
    hoverClass: "hover:bg-yellow-600",
    txtClass: "text-yellow-500",
    borderClass: "border-yellow-500",
  },
  lime: {
    name: "lime",
    displayName: "Lime",
    hex: "#84cc16",
    bgClass: "bg-lime-500",
    hoverClass: "hover:bg-lime-600",
    txtClass: "text-lime-500",
    borderClass: "border-lime-500",
  },
  green: {
    name: "green",
    displayName: "Green",
    hex: "#22c55e",
    bgClass: "bg-green-500",
    hoverClass: "hover:bg-green-600",
    txtClass: "text-green-500",
    borderClass: "border-green-500",
  },
  emerald: {
    name: "emerald",
    displayName: "Emerald",
    hex: "#10b981",
    bgClass: "bg-emerald-500",
    hoverClass: "hover:bg-emerald-600",
    txtClass: "text-emerald-500",
    borderClass: "border-emerald-500",
  },
  teal: {
    name: "teal",
    displayName: "Teal",
    hex: "#14b8a6",
    bgClass: "bg-teal-500",
    hoverClass: "hover:bg-teal-600",
    txtClass: "text-teal-500",
    borderClass: "border-teal-500",
  },
  cyan: {
    name: "cyan",
    displayName: "Cyan",
    hex: "#06b6d4",
    bgClass: "bg-cyan-500",
    hoverClass: "hover:bg-cyan-600",
    txtClass: "text-cyan-500",
    borderClass: "border-cyan-500",
  },
  sky: {
    name: "sky",
    displayName: "Sky",
    hex: "#0ea5e9",
    bgClass: "bg-sky-500",
    hoverClass: "hover:bg-sky-600",
    txtClass: "text-sky-500",
    borderClass: "border-sky-500",
  },
  blue: {
    name: "blue",
    displayName: "Blue",
    hex: "#3b82f6",
    bgClass: "bg-blue-500",
    hoverClass: "hover:bg-blue-600",
    txtClass: "text-blue-500",
    borderClass: "border-blue-500",
  },
  indigo: {
    name: "indigo",
    displayName: "Indigo",
    hex: "#6366f1",
    bgClass: "bg-indigo-500",
    hoverClass: "hover:bg-indigo-600",
    txtClass: "text-indigo-500",
    borderClass: "border-indigo-500",
  },
  violet: {
    name: "violet",
    displayName: "Violet",
    hex: "#8b5cf6",
    bgClass: "bg-violet-500",
    hoverClass: "hover:bg-violet-600",
    txtClass: "text-violet-500",
    borderClass: "border-violet-500",
  },
  purple: {
    name: "purple",
    displayName: "Purple",
    hex: "#a855f7",
    bgClass: "bg-purple-500",
    hoverClass: "hover:bg-purple-600",
    txtClass: "text-purple-500",
    borderClass: "border-purple-500",
  },
  fuchsia: {
    name: "fuchsia",
    displayName: "Fuchsia",
    hex: "#d946ef",
    bgClass: "bg-fuchsia-500",
    hoverClass: "hover:bg-fuchsia-600",
    txtClass: "text-fuchsia-500",
    borderClass: "border-fuchsia-500",
  },
  pink: {
    name: "pink",
    displayName: "Pink",
    hex: "#ec4899",
    bgClass: "bg-pink-500",
    hoverClass: "hover:bg-pink-600",
    txtClass: "text-pink-500",
    borderClass: "border-pink-500",
  },
  rose: {
    name: "rose",
    displayName: "Rose",
    hex: "#f43f5e",
    bgClass: "bg-rose-500",
    hoverClass: "hover:bg-rose-600",
    txtClass: "text-rose-500",
    borderClass: "border-rose-500",
  },
};